### ISSUE TITLE
Degrade gracefully if perlin1:get_2d is nil

### ISSUE THREAD

**Issue by mk-pmb** [ronoaldo/tsm_pyramids#2]
Originally [reported here](https://github.com/minetest/minetest/issues/10385#issuecomment-1674133548) about

https://github.com/ronoaldo/tsm_pyramids/blob/d4d89c5cc4c4bcb02eae3436454632b2ad185ddf/init.lua#L336

Some users seem to have circumstances in which `perlin1:get_2d` can be nil. It may or may not be due to interference from other mods.

If it's an essential feature (it seems it is), probably the only safe graceful way is to log an error message and give up. Optionally we could additionally greet all joining players with a chat message about why there will be no pyramids.

**Comment by ronoaldo** [comment]
Hello! Thank you for the report but this is a fork of the upstream project that I made in order to have stable releases and apply small fixes/patches for my server. Kindly look up for the upstream at https://codeberg.org/Wuzzy/minetest_tsm_pyramids

Best regards,

**Comment by mk-pmb** [comment]
Thanks! Would be nice if you could update the GitHub repo description to give the info about upstream on first glance.

Since I'm not personally invested in this, I hope someone else can report the issue to upstream.

**Comment by ronoaldo** [comment]
Done! Added this info. Since this was forked outside of Github, it does not adds such references by default as it did with other projects.

Anyways, thanks for the heads up.
